### ISSUE TITLE
Compatibillity with RN0.28

### ISSUE THREAD

**Issue by shawnpanda** [lelandrichardson/react-native-maps#331] opened 2016-06-27 06:44 UTC
I have upgraded my react native version to RN0.28 and wanted to do a simple exercise with react-native-maps. Currently, I have followed the [instruction](https://github.com/lelandrichardson/react-native-maps/blob/master/docs/installation.md) and have used both rnpm and manual processes to check whether the files are set up correctly (I am using a physical android device). After following the suggestion on [issue](https://github.com/lelandrichardson/react-native-maps/issues/288) where I avoided the following error:
`* What went wrong:
A problem occurred configuring project ':app'.
> Cannot evaluate module react-native-maps : Configuration with name 'default' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.`

However, i am currently seeing :
`
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> A problem occurred configuring project ':react-native-maps'.
   > Failed to notify project evaluation listener.
      > Could not resolve all dependencies for configuration ':react-native-maps:_debugCompile'.
         > Could not find com.facebook.react:react-native:0.27.2.
           Searched in the following locations:
               file:/Users/Shawn/.m2/repository/com/facebook/react/react-native/0.27.2/react-native-0.27.2.pom
               file:/Users/Shawn/.m2/repository/com/facebook/react/react-native/0.27.2/react-native-0.27.2.jar
               https://jcenter.bintray.com/com/facebook/react/react-native/0.27.2/react-native-0.27.2.pom
               https://jcenter.bintray.com/com/facebook/react/react-native/0.27.2/react-native-0.27.2.jar
               file:/Users/Shawn/Documents/React/2016-Summer-Of-React-Native/GeoApp/node_modules/react-native/android/com/facebook/react/react-native/0.27.2/react-native-0.27.2.pom
               file:/Users/Shawn/Documents/React/2016-Summer-Of-React-Native/GeoApp/node_modules/react-native/android/com/facebook/react/react-native/0.27.2/react-native-0.27.2.jar
               file:/Users/Shawn/Library/Android/sdk/extras/android/m2repository/com/facebook/react/react-native/0.27.2/react-native-0.27.2.pom
               file:/Users/Shawn/Library/Android/sdk/extras/android/m2repository/com/facebook/react/react-native/0.27.2/react-native-0.27.2.jar
               file:/Users/Shawn/Library/Android/sdk/extras/google/m2repository/com/facebook/react/react-native/0.27.2/react-native-0.27.2.pom
               file:/Users/Shawn/Library/Android/sdk/extras/google/m2repository/com/facebook/react/react-native/0.27.2/react-native-0.27.2.jar
           Required by:
               GeoApp:react-native-maps:unspecified
      > No such property: GROUP for class: org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
`

My question is whether the current react-native-maps doesn't support RN 0.28.0 yet. My app is entirely new and haven't added any other dependency. Would appreciate any help!

**Comment by jeveloper** [comment] 2016-06-27 20:40
Here is your solution:

go to android app , build.gradle

and change 
 compile "com.facebook.react:react-native:0.27.2"

to 0.28 (whatever the minor version is currently installed in your project)

Not a map lib issue.

**Comment by 3LP** [comment] 2016-06-27 20:58
+1.  Solution did not work.

**Comment by shawniscool** [comment] 2016-06-27 21:03
Hey @jeveloper , thanks a lot for the suggestion! In my android/app/build.gradle, i initially had 
`compile "com.facebook.react:react-native:+"  // From node_modules`.
After changing it to `compile "com.facebook.react:react-native:0.28.0"`, I am still seeing the same error as before. 

I did a grep command searching for any line in android folder that specifies version `0.27.2` but didn't find any.

**Comment by chrisv95** [comment] 2016-06-27 21:49
I'm having the same issue, i.e.
 > Could not find com.facebook.react:react-native:0.27.2.

Hence, I think it's not React Native that's causing the issue, but the configuration of react-native-maps, because:
 > Could not resolve all dependencies for configuration ':react-native-maps:_debugCompile'.

Therefore, changing React 0.27 or + into 0.28 does not work, and we should take a look into the way react-native-maps is compiled.

I solved it this way:
in
node_modules/react-native-maps/package.json
node_modules/react-native-maps/android/lib/build.gradle

change 0.27.2 into 0.28.0
... and build again!

Currently, only
> A problem occurred configuring project ':react-native-maps'.
   > No such property: GROUP for class: org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer

is left, but I'm not sure whether this is caused by this error.

**Comment by skellock** [comment] 2016-06-28 14:30
Here's what I have for a solution to run on 0.28 until this gets patched up.

Half the answer is https://github.com/lelandrichardson/react-native-maps/pull/335

And half the answer is what @jeveloper mentioned.

I have a fork & branch with these applied.

So, on `react-native 0.28` with a fresh project, do this:

`npm i --save skellock/react-native-maps#friends-with-28` <-- with bash
`npm i --save skellock/react-native-maps\#friends-with-28` <-- or with zsh

Followed by a `react-native link react-native-maps`.

Then open your `android/settings.gradle` and add `/lib` to the `project` entry for maps:

`project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/android/lib')`

Next, open `android/src/main/java/com/<PROJECT NAME>/MainActivity.java` and change `new MapsPackage()` to the old style `new MapsPackage(this)`.

That'll get you up & running on 0.28 until we get sorted officially.

**Comment by GantMan** [comment] 2016-06-28 15:09
It might be worth noting, that if you know you need a different instantiation parameter in Android, you can tell `rnpm` to do this with adding the following to your `package.json`

```
  "rnpm": {
    "android": {
      "packageInstance": "new MapsPackage(this)"
    }
  },
```

super kudos @skellock for digging into a 0.28 solution!

**Comment by skellock** [comment] 2016-06-28 15:11
Oh wow.  I did not know that @GantMan !

**Comment by ahmed1490** [comment] 2016-06-29 01:13
I was getting the same error in v0.27.2. @skellock suggestion solves the issue! Cheers! :D

**Comment by shawniscool** [comment] 2016-06-29 03:18
Following the instruction from @skellock solved the issue. Closing the issue.

**Comment by kevinvangelder** [comment] 2016-06-29 21:49
@shawniscool If it were me, I'd leave the issue open until @skellock's fix is integrated into this repository. Loading an NPM module from a third party isn't ideal unless the original is no longer being maintained.

**Comment by shawniscool** [comment] 2016-06-29 23:16
whoops. Thanks @kevinvangelder

**Comment by ryanhomer** [comment] 2016-06-30 00:32
Just a note that I get the same issue even with RN 0.27.0. I'm seeing reference to 0.27.2 but that is not an official release in the RN repo. It goes from 0.26.3 to 0.27.0 to 0.28.0.

Anyway, hopefully an official fix will come soon.

**Comment by chrisv95** [comment] 2016-07-01 08:24
Any indication on when a fix would be released?

**Comment by stoffern** [comment] 2016-07-11 07:11
PR to fix this issue is merged: https://github.com/lelandrichardson/react-native-maps/pull/363

**Comment by felipecsl** [comment] 2016-09-08 20:05
This should be already fixed. Closing

**Closed by felipecsl** 2016-09-08 20:05 UTC
