### ISSUE TITLE
Updating causes `Configuration with name 'default' not found.` error on Android

### ISSUE THREAD

**Issue by 7mllm7** [lelandrichardson/react-native-maps#332] opened 2016-06-27 09:18 UTC
Updated from 0.4.2 to 0.6.0, Android stopped working with the error `Configuration with name 'default' not found.` upon `react-native run-android`.

I found that before updating the version of `react-native-maps`, one must:

1. `rnpm unlink react-native-maps`.
2. `npm install react-native-maps@latest --save`.
3. `rnpm link react-native-maps`.

I even had to manually delete `new AirPackage()` and `import com.AirMaps.AirPackage;
` from `MainActivity.java`.

**Comment by 1ne8ight7even** [comment] 2016-06-28 16:33
Same here, but your solution won't fit for me.

**Comment by kevinvangelder** [comment] 2016-06-29 00:40
This is a duplicate of #331

**Comment by jrichardlai** [comment] 2016-06-29 04:36
closing this for now as its a duplicate of https://github.com/lelandrichardson/react-native-maps/issues/331

**Closed by jrichardlai** 2016-06-29 04:36 UTC
