### ISSUE TITLE
Memory leak on Android

### ISSUE THREAD

**Issue by sodik82** [lelandrichardson/react-native-maps#95] opened 2016-02-24 15:07 UTC
Hi there,

I mount and unmount `<MapView>` component (with single marker) quite often. And during my test on real device the app is killed after some time by OS. I have investigated it more and found out that the memory usage is really high (I can get to 1.5GB after 25-30 cycles).

```
Applications Memory Usage (kB):
Uptime: 199716698 Realtime: 1702619320

** MEMINFO in pid 10768 [com.nativevibe] **
                   Pss  Private  Private  Swapped     Heap     Heap     Heap
                 Total    Dirty    Clean    Dirty     Size    Alloc     Free
                ------   ------   ------   ------   ------   ------   ------
  Native Heap        0        0        0        0    60402    60402    20493
  Dalvik Heap      165      104        0    82120   100544    84443    16101
 Dalvik Other        0        0        0      332                           
        Stack       68       68        0     1008                           
    Other dev   367039   366772       36        0                           
     .so mmap      409       12      148     2188                           
    .apk mmap       30        0        0        0                           
    .dex mmap       41        0        8        0                           
    code mmap      409        0        0        0                           
   image mmap      546       12        4     1876                           
   Other mmap       13        0        0        8                           
     Graphics    33444    33444        0        0                           
           GL   515760   515760        0        0                           
      Unknown      305      296        0    67744                           
        TOTAL   918229   916468      196   155276   160946   144845    36594
```

I am on Samsung S4 - Android 5.0.1. Quite funny is that same apk on different phone does not lead to such catastrophic results - the memory usage is still increasing but not in a such radical way.

Official documentation of [GMap](https://developers.google.com/android/reference/com/google/android/gms/maps/MapView) claims that the Users of this class must forward all the life cycle methods from the Activity or Fragment.

So I did make some experiments and I have added following code to `AirMapManager`

```
    @Override
    public void onDropViewInstance(AirMapView view) {
        super.onDropViewInstance(view);
        view.onDestroy();
    }
```

and it helped to significantly reduce the memory overhead - however the results were not perfect. However I don't know if it is the "right" place to call such method since I don't know the internals of react-native or to verify that onDestroy is really called since the method is final in `AirMapView`

**Comment by lelandrichardson** [comment] 2016-02-25 19:41
Hi @sodik82 ,

Thanks for looking into this issue!  Do you think you could put up a PR of the change?

Also, cc'ing @mkonicek to see if he can confirm that this would be an appropriate place to put this

**Comment by sodik82** [comment] 2016-02-25 20:46
sure, I can create PR for this. However some review would be helpful as it was just some empirical experiment :)

**Comment by bcalik** [comment] 2016-02-25 20:48
I have the same problem and just came here to report that. After a few mount and unmount, my app gets really slow and becomes unresponsive, after that the app get killed by OS.

Please create PR, so I will also do testing.

**Comment by sodik82** [comment] 2016-02-25 21:34
PR created.

**Comment by experimentsin** [comment] 2016-03-14 18:25
The linked PR for this seems to have stalled in review, which is a little bit unfortunate given the severity of the problem on Android. Is it likely to get review attention?

**Comment by lelandrichardson** [comment] 2016-03-14 18:27
@experimentsin thanks for the ping. I agree we should get this PR in. I will take a look today and merge + publish if all looks good.

Thanks for your patience.

**Comment by experimentsin** [comment] 2016-03-14 19:46
No pressure, I just think @sodik82's done some good work tracking down the issue and it would be great for everyone to benefit. Thanks for giving it the once over.

**Comment by sodik82** [comment] 2016-03-14 21:24
@experimentsin thanks for your valueable input on PR @bcalik can you confirm any improvement on the matter?

**Comment by bcalik** [comment] 2016-03-14 21:45
@sodik82 I don't know, I am not sure. There are still memory issues, but this pr feels like reduced it a little. Anyway I released my app on both Android and iOS, our clients are using it and there isn't any negative feedback yet.

**Comment by JamesWatling** [comment] 2016-04-02 09:28
@sodik82 This has improved the leaks, but they're still quite prevalent, and on some devices (mostly tablets) the app becomes unresponsive quite quickly

**Comment by sodik82** [comment] 2016-04-02 14:14
thanks for report. I am also not convinced that current solution removed all leaks. Therefore I am leaving the issue open and hoping that someone more experienced can bring more light on the subject.

**Comment by DennisMG** [comment] 2016-05-27 22:34
I noticed that the HashMap "markerMap" in AirMapView.java is not removing the markers on `removeFeatureAt`. This is causing the memory leak. I replaced `markerMap.remove(feature.getFeature())` with `markerMap.clear();` (just for testing) and it reduced the memory leak a lot! Also I noticed feature.getFeature() always returns null... I don't think this is the best "fix" but it helped me a lot. Maybe someone with more experience can take a look at this. 👍  
:)

**Comment by DennisMG** [comment] 2016-05-30 21:56
I found the problem! 
```

public void removeFeatureAt(int index) {
        AirMapFeature feature = features.remove(index);
        feature.removeFromMap(map); // <--- remove this

        if (feature instanceof AirMapMarker) {
            markerMap.remove(feature.getFeature());
        } else if (feature instanceof AirMapPolyline) {
            polylineMap.remove(feature.getFeature());
        } else if (feature instanceof AirMapPolygon) {
            polygonMap.remove(feature.getFeature());
        } else if (feature instanceof AirMapCircle) {
            circleMap.remove(feature.getFeature());
        }
       feature.removeFromMap(map); //<--- Add this
    }
```

I just changed `feature.removeFromMap(map);` to the end of the function!! I don't know if this was made by design or nobody has noticed yet!! 

Please correct me if i'm wrong!!


@lelandrichardson @sodik82

**Comment by sodik82** [comment] 2016-05-31 08:48
ah... at first look the change does not seem to be relevant but you are actually right :)

when I check e.g. implementation of `AirMapMarker` I can see following

```
    @Override
    public Object getFeature() {
        return marker;
    }

    @Override
    public void removeFromMap(GoogleMap map) {
        marker.remove();
        marker = null;
    }
```

thus if you call `removeFromMap` first, then the call `getFeature` will return `null` and therefore leaving the marker in the map.

My guess is that the same problem can happen for other features.

@DennisMG do you want to make simple PR for this?
@lelandrichardson are you okey with this fix?

**Comment by DennisMG** [comment] 2016-05-31 15:52
PR created! 👍

**Comment by jrichardlai** [comment] 2016-06-01 05:40
Thank you for investigating @sodik82 and @DennisMG. Merged the fix.

**Closed by jrichardlai** 2016-06-01 05:40 UTC
