### ISSUE TITLE
Document `followUserLocation` (Boolean)

### ISSUE THREAD

**Issue by niftylettuce** [lelandrichardson/react-native-maps#78] opened 2016-02-15 05:31 UTC
Right now it's not documented under <https://github.com/lelandrichardson/react-native-maps/blob/master/docs/mapview.md>.  In order to disable following on iOS, this is needed (had to dig up the React Native docs that have it, to then realize it's also a prop in this lib).

**Comment by niftylettuce** [comment] 2016-02-15 05:35
Is this a bug?  If you pass `false`, then it will still follow location despite this code <https://github.com/lelandrichardson/react-native-maps/blob/124039be1808a67e842d6bafa71d01b94431930d/ios/AirMaps/AIRMapManager.m#L314-L323>.  So we have to enable it to true, in order it to get disabled?

**Comment by niftylettuce** [comment] 2016-02-15 06:31
It also needs patched too, see this comment on StackOverflow (it was broken in RN v0.19 and the files AIRMAP.h and others need patched too).

<http://stackoverflow.com/a/35233142>

**Comment by niftylettuce** [comment] 2016-02-15 06:31
Also, I think the iOS emulator automatically adjusts/centers MapView if you are running simulation of a car driving.  I have tested with bike and walking simulations (with geolocation on Simulator), and it seems that it only occurs for driving.  In other words, if you do bike/run in Simulator, it does not follow the user and re-center the map, however on driving mode it does.

**Comment by ahmed1490** [comment] 2016-02-17 00:49
related https://github.com/lelandrichardson/react-native-maps/issues/53

**Comment by christopherdro** [comment] 2016-03-02 16:57
Closing since this is a duplicate of #53.

**Closed by christopherdro** 2016-03-02 16:57 UTC
