### ISSUE TITLE
Android: Pushing view with mapview on existing mapview

### ISSUE THREAD

**Issue by sai-prasanna** [lelandrichardson/react-native-maps#207] opened 2016-05-03 17:02 UTC
Hi,
When I push a view on navigation stack(using React Native Experimental Router  or React Native Flux Router), if first view, and the view that is being pushed have MapViews,
the first map view persists in the second view. This happens only in android.

**Comment by sai-prasanna** [comment] 2016-05-05 06:39
For example 

View A -> has a map view m1
View B -> has a map view m2

If View B is pushed on to View A using React Native Router (Navigation Scene) , 
The View B map shows contents of View A map , and is un responsive to touches

**Comment by mvaivre** [comment] 2016-05-13 08:37
Same problem for me. Seems related to https://github.com/aksonov/react-native-router-flux/issues/489.
The Scene is re-mounted when navigating in, creating a new MapView instance.

**Comment by mvaivre** [comment] 2016-05-28 09:36
@sai-prasanna Did you manage to find a hack to bypass this issue?

**Comment by sai-prasanna** [comment] 2016-05-31 05:47
@mvaivre Unfortunately no, I was working on it for a side project, and didn't have time to find  a hack or even analyse the issue

**Comment by jburich** [comment] 2016-06-21 21:48
@sai-prasanna any chance you found a work around? I just hit this too.

**Comment by jeveloper** [comment] 2016-06-23 04:36
+1 even with 0.6 , same thing, any hacks?
thanks

**Comment by sai-prasanna** [comment] 2016-06-23 06:01
Sorry no progress yet, I was using it only for pet project.

Let us try to debug this.

As @mvaivre pointed out this may be bug in react native router flux or react native experimental navigation.  Checkout that thread first ..

Can you guys check out wether this happens to other components?

**Comment by jburich** [comment] 2016-06-23 15:25
I have several different component types on my home screen. Each one clicks through to different screens. The only one that is a problem is the map. My other components don't draw over the top of the map at all. And if I click through to a non-map screen they look fine. So its only going from Screen A that has a map (and possibly other things) to Screen B that is a full screen map.

Worth noting is that I was running really out-dated versions of everything. We were on react-native 0.22 and upgraded to react-native 0.27 which triggered a pretty massive waterfall of updating react-native-router-flux, react-native-maps and a whole lot of other packages that were are using. Until I upgraded everything the app wouldn't even start so I cannot narrow down which upgrade it was that caused the problem.

I've had to move onto a different task for this week, but am happy to assist debugging as I can, and will be back to dedicating my time to getting this working next week.

**Comment by jeveloper** [comment] 2016-06-24 02:04
By the way, i noticed that if setting key and ref to different values , it started to work. using 0.6.0 and RN 0.27.2

**Comment by pellepersson** [comment] 2016-06-28 12:31
@jeveloper - "setting the key and ref to different values" on what? Really hoping for your solution to work. :)

**Comment by jeveloper** [comment] 2016-06-28 14:27
I make sure to have different key and ref values for every map components i use between views (on mapview) , so when switching Action.someview , it forces map to be rerendered.

hope it helps

**Comment by pellepersson** [comment] 2016-06-28 15:23
@jeveloper - unfortunately not - the old mapview still gets rendered over the new one. But thanks for you quick answer!

**Comment by jeveloper** [comment] 2016-06-28 23:42
try making the key a random variable and upon componentmount setState to that variable 
i did this to refresh markers and circle , basically a trick

**Comment by pellepersson** [comment] 2016-06-29 11:03
@jeveloper - after upgrading everything I could in my project to the latest versions (RN, react-native-router-flux etc...) it now works just fine. I am not sure if it is the fixes you suggested or if it was a fix in some of the other libraries that fixed it. Will try to figure this out after I have taken care of the other issues the upgrades created and get back to you. Thank you for your help anyways!

**Comment by pellepersson** [comment] 2016-06-29 13:54
@jeveloper - turns out that there were no need for separate components and such in my case. Maybe we have different versions of something... By upgrading to RN 0.28, using skellocks version of react-native-maps (github:skellock/react-native-maps#friends-with-28) and react-native-router-flux 3.30.3 everything works as it should.

**Comment by jeveloper** [comment] 2016-07-28 23:13
Anyone with luck on this , RN 30 + flux 32 and Map 0.7.1
Still able to reproduce this issue, map simply is on top of the currently added view

**Comment by jeveloper** [comment] 2016-07-28 23:24
@jburich any luck on your end?
@pellepersson  .28 works but 29 and 30 with latest map (which cant work without RN 29+) does not

thanks

**Comment by jburich** [comment] 2016-07-29 12:14
no luck here, but I've been forced to move onto a new project until at least the beginning of August and maybe longer :( Hoping to get back to react native work soon.

**Comment by jeveloper** [comment] 2016-07-29 19:59
By the way i did some more digging on this, filed a ticket with flux as i believe it might be responsible for the bug
https://github.com/aksonov/react-native-router-flux/issues/989

**Comment by danscan** [comment] 2016-08-17 00:32
This issue appears to have nothing to do with `react-native-router-flux` in particular, but rather is related to `NavigationExperimental`...

I just tested this with `NavigationExperimental.CardStack` and `react-native@0.31` (**without** `react-native-router-flux`).  The issue still occurs.

Example component: 
```javascript
import { NavigationExperimental } from 'react-native';
import MapView from 'react-native-maps';

export default () => (
  <NavigationExperimental.CardStack
    navigationState={{
      index: 0,
      routes: [
        { key: 'MAP_1' },
        { key: 'MAP_2' },
        { key: 'MAP_3' },
      ],
    }}
    renderScene={() => (
      <MapView style={{ flex: 1 }} />
    )}
  />
);
```

When the `index` (in the `navigationState` object) is `0` (i.e. the root route is the current route, and the only route rendered), the map works fine:
![reactnativemapsnavigationexperimentaltestindex0](https://cloud.githubusercontent.com/assets/1638987/17720447/fc54b2d4-63ef-11e6-9d45-4dcaec526d5d.gif)

When the `index` is `1` (i.e., a second route was pushed, and is now the current route (and the previous route is rendered behind it), the issue occurs:
![reactnativemapsnavigationexperimentaltestindex1](https://cloud.githubusercontent.com/assets/1638987/17720442/ed8c5e96-63ef-11e6-8ee9-268472f2674e.gif)

**Comment by jeveloper** [comment] 2016-08-17 15:54
@lelandrichardson  Would you guys make a comment on this issue please
Thank you

I'd love to donate to support the project , or since AirBnb is so busy, perhaps a those active folks (with pull requests ) should be granted control.

**Comment by danscan** [comment] 2016-08-17 22:45
@jeveloper I've drilled down some more on this issue.  It turns out to have nothing to do with `react-native-router-flux`, or `NavigationExperimental`, or even `position: 'absolute'`.  

It appears that this issue occurs when the (x;y) area of multiple `MapView` instances overlap at any place in the view hierarchy.  When this happens, the maps are drawn in the incorrect order on the z-axis.  The touch events are actually going to the correct `MapView` instance, but it is just rendered beneath another `MapView` instance that is at a lower position in the element tree.

**Comment by jeveloper** [comment] 2016-08-18 14:41
@danscan  awesome find , i think i saw a similar issue in my tests, you can see the other map partially when playing with absolute postions and offsetting one or another.
i havent personally looked into this map source code that much , is this happening in java code or elsewhere? do you want to pair up and fix it?

**Comment by pellepersson** [comment] 2016-08-18 17:22
When I upgraded to latest versions of everything, this issue appeared again.

And @danscan - I think that you are totally right. I guess it is not that normal that people are using multiple instances of the MapView since this is not fixed yet. :)

Please let me know how it goes on your end. I will give it some more thought now and let you know if I find something you have not already found.

**Comment by Lube** [comment] 2016-09-09 16:19
No news or workarounds for this on RN 0.32.0 right?

**Comment by felipecsl** [comment] 2016-09-09 19:05
This sounds like a duplicate of #453, no?

**Comment by jeveloper** [comment] 2016-09-09 19:25
@felipecsl  yes it is :)

**Comment by felipecsl** [comment] 2016-09-09 19:31
Alright I'll close it as duplicate then, lets continue the discussion on #453

**Closed by felipecsl** 2016-09-09 19:31 UTC
Labels: duplicate
