### ISSUE TITLE
Disabling compass doesn't work on iOS < 9

### ISSUE THREAD

**Issue by rops** [lelandrichardson/react-native-maps#243] opened 2016-05-20 18:45 UTC
Setting `showsCompass={false}` on iOS < 9 causes a crash.

```
-[AIRMap setShowsCompass:]: unrecognized selector sent to instance 0x122280c40
```

`setShowsCompass` is only supported on iOS >= 9

**Comment by christopherdro** [comment] 2016-05-24 06:01
@rops What version are you using?

Looks like this was merged and made available in 0.5.0

https://github.com/lelandrichardson/react-native-maps/commit/edfa2b42ce40369d19b27cc2a9c835491ba3793b

Can you try installing that version and see if the problem is fixed.

**Closed** 2016-06-16 06:33 UTC
